### ISSUE TITLE
pdflatex code 134

### ISSUE THREAD

**Issue by movsky** [bobvandevijver/latex-bundle#14]
Hey,

i'm trying to use your bundle to generate pdfs from a texfile. But I always get an error message when generating the pdf file:

> Something went wrong during the execution of the pdflatex command, as it returned 134.

When I use pdflatex from the terminal with exactly the same texfile it all works well. Do you have any idea what could cause this problem? Cache and stuff is all writeable. Also the folder where pdf is going to be created.

That's my code:

Controller:
```php
/**
  * @Route("/pdf")
  * @Template()
  *
  */
public function pdfAction() {
        $texLocation = '/var/www/xrbs/tex/samplefile.tex';
         
        $latexGenerator = $this->get('bobv.latex.generator');
        $pdfLocation = $latexGenerator->generatePdf($texLocation);
        echo $pdfLocation;
}
```

**Comment by movsky** [comment]
And there is no logfile generated by the way.

**Comment by bobvandevijver** [comment]
Hi there, 

I've been looking for you what the possible problem could be. The error-code indicates that there is something wrong with the execution of the pdflatex command, but I can not find what the specific error-code means. However, the error should also give you a location of the log file, so what does it say?

You are trying to compile a tex file on a specific location. This means that all logging and output should be generated in that directory (is that what you want?). It might be that the log file or the output file cannot be opened, as of a permissions problem, or that your webserver user is not allowed to execute anything outside of your PHP code. 

Can you try to replace [line 275](https://github.com/bobvandevijver/latex-bundle/blob/master/Generator/LatexGenerator.php#L275) with the following, and post back the output here?

```php
$command = "cd " . $this->outputDir . " && pdflatex " . $optionsString . " -interaction=nonstopmode -output-directory=\"" . $this->outputDir . "\" \"$texLocation\"";
echo $command . "\n\n";
exec($command, $output, $result);
var_dump($result);
echo "\n\n";
var_dump($output);
```

You can edit the file in `$sf_root$/vendor/bobv/latex-bundle/BobV/LatexBundle/Generator/LatexGenerator`. 

You might also try running the command printed by the above code directly on your machine, maybe the problem is caused by one of the options given.

**Comment by edrush** [comment]
Hi, 

I'm having a similar issue: no log file, no pdf generated, eeor code 1. When I execute the command directly it works great.

My output:


"cd E:\...\app\cache\dev/BobVLatex/03a59ec1fca66a2b44a2238ce17adea0587e2483 && pdflatex  -interaction=nonstopmode -output-directory="E:\...\app\cache\dev/BobVLatex/03a59ec1fca66a2b44a2238ce17adea0587e2483" "E:\...\app\cache\dev/BobVLatex/03a59ec1fca66a2b44a2238ce17adea0587e2483/Announcement.tex"

int(1)


array(0) {
}"

My environments: Xampp (older version) on Win7, Xampp (current) on Mac OS X 10.9

Seems to be a permission problem? Maybe there is a exec function coming from Symfony to support permissions?

Best regards!

**Comment by edrush** [comment]
Hi,

I solved mine, pdflatex was simply not in the PHP Path yet...I got this information  when I used http://symfony.com/doc/current/components/process.html instead of exec() in LatexGenerator, maybe you can integrate that?

Thanks!

**Comment by bobvandevijver** [comment]
@edrush I guess that is a nice addition! I will look into that :+1:

**Comment by edrush** [comment]
Nice! 

For people having the same problem and using Xampp: the solution was to simply restart Xampp to have the path available after installing MiKTeX.
