### ISSUE TITLE
Define .pdf/.tex saving folder

### ISSUE THREAD

**Issue by mario6097** [bobvandevijver/latex-bundle#18]
Hi
Nice tool.
I am trying to understand how I may configure it as to save pdf and tex outputs within my own bundle directory and/or the web directory of symfony (instead of within app/cache/dev/BobVLatex).
Do I need to hack the code (which is bad   for updates)

**Comment by bobvandevijver** [comment]
All output is generated by one service: the [generator](https://github.com/bobvandevijver/latex-bundle/blob/master/Generator/LatexGenerator.php) service. You can simply override the service definition of [`bobv.latex.generator`](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/config/services.yml#L8) and replace the first argument with one of your own. 

However, note that the postfix `BobVLatex` will still be added, but if you want to change that you can extend the Generator class and overwrite the [`getCacheBasePath()`](https://github.com/bobvandevijver/latex-bundle/blob/master/Generator/LatexGenerator.php#L302) method.

Finally, you should also consider that the cache directory is used for a reason: to generate a correct PDF file, all [dependencies](https://github.com/bobvandevijver/latex-bundle/blob/master/Generator/LatexGenerator.php#L153) (if any, like fonts, letterhead, ...) are also placed there. By placing it in the cache, we know it can easily and automatically will be removed so that the disk does not constantly fill up. If you want to have the PDF in a specific location, it might be better to simply copy it by yourself after generation, as the `generatePdf` method will return its complete location.

**Comment by mario6097** [comment]
Hi Bob, 
thanks for your reply.
Sorry for my ignorance: how do override the service definition? I mean, how do I define a parameter to point to MyBundle/../Resources/Public/Pdf ? Is that somewhere in the documentation at symfony.com? 
Anyway, the right way of doing this is indeed by Copy.

**Comment by bobvandevijver** [comment]
For overriding any part of any bundle take a look at the [Symfony docs](http://symfony.com/doc/current/cookbook/bundles/override.html). In this case, the neatest solution would be a CompilerPass, but simply overwriting the services definition in a bundle loaded later is also possible. 

The latter would look like this (in your AppBundle which is loaded in the AppKernel after the Latex Bundle):
```yaml
services:
  bobv.latex.generator:
    class: %bobv.latex.generator.class%
    arguments: [ "/var/www/web/yourdir", %kernel.environment% ,"@twig", %bobv.latex.max_age% ]
```

Or, set the `%bobv.latex.generator.class% parameter in your `config.yml`/`parameters.yml` in the `app/config` directory to your custom class, which extends the original generator in which you overwrite the `getCacheBasePath()` to return the own path (actually found a little bug in the code which I've fixed now'. 

So, a lot of options ;) But still, the copy would be the way to go.

**Comment by bobvandevijver** [comment]
@mario6097 I've added a parameter which can be used to easily overwrite the default cache dir!
